### ISSUE TITLE
Exception reported: Client index 0 is invalid

### ISSUE THREAD

**Issue by gmmanonymus111** [JoinedSenses/TF2-SetClass#1]
When plugin is used from server console, it gives this error, and sets only 1 player's class.
```
sm_setclass @all random
L 02/26/2019 - 19:41:25: [SM] Exception reported: Client index 0 is invalid
L 02/26/2019 - 19:41:25: [SM] Blaming: setclass.smx
L 02/26/2019 - 19:41:25: [SM] Call stack trace:
L 02/26/2019 - 19:41:25: [SM]   [0] GetClientUserId
L 02/26/2019 - 19:41:25: [SM]   [1] Line 84, G:\Documents\TF2\SourceMod 1.9.0-6245\addons\sourcemod\scripting\setclass.sp::Command_Setclass
```

**Comment by JoinedSenses** [comment]
Should be fixed now with the newest commit: https://github.com/JoinedSenses/TF2-SetClass/commit/312d3252491cb38ae6b004fb77508870e79bc6e2

Unfortunately I never tested using (sm_)rcon and didn't catch this, so thank you. There was a copy/paste error and `client` should have been `i`. If you have any other problems, please let me know.

edit: https://github.com/JoinedSenses/TF2-SetClass/commit/c92020ca4c92f5719c358320b20193fb00bc91f0
** `target_list[i]` instead of `i`
